### ISSUE TITLE
Clarify `failIfMajorPerformanceCaveat`

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-supported#10]
@lucaswoj can we clarify in the readme what `failIfMajorPerformanceCaveat` means?

**Comment by lucaswoj** [comment]
:+1: I agree that we should document the API in `README.md`. 

Is the language in the [documentation comment](https://github.com/mapbox/mapbox-gl-supported/blob/gh-pages/index.js#L13-15) sufficiently clear?

```
/**
 * Test whether the current browser supports Mapbox GL JS
 * @param {Object} options
 * @param {boolean} [options.failIfMajorPerformanceCaveat=false] Return `false`
 *   if the performance of Mapbox GL JS would be dramatically worse than
 *   expected (i.e. a software renderer is would be used)
 * @return {boolean}
 */
```

**Comment by mourner** [comment]
This is documented by the WebGL spec, not specific to Mapbox GL JS https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1
