### ISSUE TITLE
Can't find variable: Uint8ClampedArray in safari

### ISSUE THREAD

**Issue by achalnexus** [mapbox/mapbox-gl-supported#12]
i am using gl-mapbox and i got error "Uint8ClampedArray" and "ReferenceError: Can't find variable: mapboxgl " in safari browser.

I am using this version GL-Jquery.

<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.21.0/mapbox-gl.js'></script>

<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.21.0/mapbox-gl.css' rel='stylesheet' />

Open this link "https://dev1.usedirect.com/Californiamapbox" and right click on page and select Inspect element you can see error..

**Comment by jfirebaugh** [comment]
I can't replicate the issue. The only error I see in the Safari developer tools is a 404 on `bootstrap-select.css.map`.

If you believe there is a bug here, please create a minimal, self-contained example on JSFiddle.
