### ISSUE TITLE
Is there a benefit to using this over .supported() in mapbox/mapbox-gl?

### ISSUE THREAD

**Issue by sahandnayebaziz** [mapbox/mapbox-gl-supported#13]
Hi everybody, today we started using the `supported()` method of mapbox-gl to check support before showing mapbox on an older version of Firefox that was throwing exceptions. After checking for support, the older version of Firefox is working great and skipping the map. But we still see some warnings.

Are those warnings that are logged in the process of checking support? Does this library do that differently?

**Comment by sahandnayebaziz** [comment]
I just looked at the source for mapboxgl and saw that this library is required there :) 

https://github.com/mapbox/mapbox-gl-js/blob/1926aa502302bf82b606836f0eac709d3e45690b/js/util/browser.js#L84

I will leave this issue open though in case there is anything else you'd like to add in response.

**Comment by jfirebaugh** [comment]
Yep -- we made mapbox-gl-supported a standalone library in case people wanted to test for support before even loading mapbox-gl.js -- otherwise there's no difference between using it directly and using the wrapper in gl.js.
