### ISSUE TITLE
test failing on default Android browser 4.4.2

### ISSUE THREAD

**Issue by Biboba** [mapbox/mapbox-gl-supported#14]
Hello, 

I tested the "mapbox-gl-supported" on Android version 4.4.2 but the test does not fail though the map is not displayed properly:
![screenshot_2017-02-10-20-13-28](https://cloud.githubusercontent.com/assets/11556423/22840394/aa658164-efcd-11e6-96de-747347207a0f.png)

The console is saying:
"WebGL : INVALID_OPERATION: drawArrays:attribs not setup correctly.
"WebGL : INVALID_OPERATION: no ELEMENT_ARRAY_BUFFER bound

I can add that on the same phone, under Chrome, the same map is displayed properly.

Should another test be added ?

Thanks

**Comment by jfirebaugh** [comment]
If this is still reproducible with the most recent version of Mapbox GL JS, please file an issue in https://github.com/mapbox/mapbox-gl-js/.
