### ISSUE TITLE
export check results

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-supported#18]
I've migrated a website to Mapbox GL JS and I'd like to show some friendlier warning to users with unsupported browsers. Such as "WebGL is not enabled" or "Please update your browser".

Right now it requires me to copy-paste the code from index.js into my own project.

I'd be nice to have `.isWebGLSupportedCached` exported as module's variables.

**Comment by harto** [comment]
This would also be useful for me to help figure out why one browser vs another isn't supported for some of our users. Occasionally we get a report that our product doesn't load in Chrome but works fine in Firefox, etc.

**Comment by harto** [comment]
Oh, I just found `diagnostics.html` in the source. That seems useful but perhaps still doesn't cover all the possible failure cases.

**Comment by harto** [comment]
Here's something I hacked together. Would it make a useful PR? https://github.com/harto/mapbox-gl-supported/commit/41d60be0ebdc001a315f125d75f0118e71e20098

**Comment by kkaefer** [comment]
Tracking in https://github.com/mapbox/mapbox-gl-supported/pull/29
