### ISSUE TITLE
ArrayBuffer.isView not checked

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-supported#19]
Some older browsers, like (Chrome Mobile  36) doesn't support ArrayBuffer.isView, yet it's required.

The error being raised is:
```
Object function ArrayBuffer() { [native code] } has no method 'isView'
```

**Comment by jfirebaugh** [comment]
In https://github.com/mapbox/mapbox-gl-supported/pull/17 it was claimed that this error message was appearing despite `ArrayBuffer.isView` existing. Is that true in Chrome Mobile 36?

**Comment by hyperknot** [comment]
I have no idea how to get an old Chrome Mobile 36 version running, this was only from a report.

**Comment by jfirebaugh** [comment]
🤷‍♂️ 

8426b3a7eff695b0efeb6adaabb3396bce11e0fd
