### ISSUE TITLE
Add Chrome on OS X 10.6.8

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-supported#20]
Chrome has been unsupported on OS X 10.6.8 for quite a while. The latest version seems to be 49.0.2623.

I'm getting reports that the compileShader part doesn't work on all those machines. It terminates with 

```
AssertionError
null == true
```

For this line:
https://github.com/mapbox/mapbox-gl-js/blob/7c951985e4d967abc048ce5568c4edd6add05c8b/src/render/program.js#L44

Do you have any idea how to detect compilation errors? Or just blacklist OS X 10.6 + Chrome?
I don't have access to any such machine here.

**Comment by kkaefer** [comment]
This should now be caught by the change in https://github.com/mapbox/mapbox-gl-supported/pull/28. Unfortunately, I don't have a machine that has an OS that's a decade out of date. If you do, I would appreciate if you could verify that it is now marked as unsupported.
