### ISSUE TITLE
detect Brave browser configurations which break mapbox gl

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-supported#25]
Two scenarios where the browser Brave breaks mapbox gl

- https://github.com/mapbox/mapbox-gl-js/issues/9186
- https://github.com/mapbox/mapbox-gl-js/issues/8377

mapbox-gl-supported should check for these limitations and return false if we're going to be unable to render the map.

**Comment by kkaefer** [comment]
@andrewharvey PR is in https://github.com/mapbox/mapbox-gl-supported/pull/28
