### ISSUE TITLE
Older versions of chrome text rendering breaks (chrome 48)

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-supported#27]
This module should fail for older versions of browser that no longer work: https://github.com/mapbox/mapbox-gl-js/issues/8742

**Comment by kkaefer** [comment]
https://github.com/mapbox/mapbox-gl-js/pull/9349 will fix this issue in very old versions of Chrome, so we no longer need to exclude Chrome 48 once it gets released.
