### ISSUE TITLE
isWebGLSupported is breaking apps on Mobile Safari 9

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-supported#32]
I'm using `mapboxgl.supported()` in an app to display a warning if map cannot work.
The problem is that since 1.5.0 it is using `gl.createShader(gl.VERTEX_SHADER)` code, which is throwing exception in Mobile Safari 9 on iPads and a bunch of other older browsers.

The exception is

```
r.createShader is not a function. (In 'r.createShader(r.VERTEX_SHADER)', 'r.createShader' is undefined)
```

This wouldn't be a big problem, but this library is supposed to detect especially these unsupported browsers without breaking the main app and unfortunately with recent release this happens.

The solution is maybe as simple as testing for `gl.createShader` first. I cannot test it, as I have no Mobile Safari / old iPads, I only see it in Sentry errors.

**Comment by asheemmamoowala** [comment]
@hyperknot Thank you for reporting this issue.

> and a bunch of other open browsers.

Can you provide the other browsers that you are seeing as affected as well?

**Comment by hyperknot** [comment]
Sure:
![image](https://user-images.githubusercontent.com/494223/84875448-481a2280-b086-11ea-9bc7-8e13bd82753e.png)

![image](https://user-images.githubusercontent.com/494223/84875496-536d4e00-b086-11ea-80df-5e95c4519599.png)

I guess the browsers are all just WebView, except macOS Safari 9 and 10.

In my own codebase I fixed this by adding: `if (!gl || !gl.createShader) {` here:

https://github.com/mapbox/mapbox-gl-supported/blob/a6410cc7c7b803f57820a22a4af8abebfa52370f/index.js#L162

**Comment by ryanhamley** [comment]
That's interesting. It would appear based on MDN's [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/createShader#Browser_compatibility) that all of those browsers support `createShader`. I don't think there's any real harm in guarding against this error though so I'll create a PR.
