### ISSUE TITLE
Mapbox-gl broken on new Chrome

### ISSUE THREAD

**Issue by KarenRei** [mapbox/mapbox-gl-supported#35]
I'm running Google Chrome version 87.0.4270.0 (Official Build) dev (64-bit), which is currently the stock build on Fedora. Apps running Mapbox-gl now no longer work.  Your detector states:

MAPBOX GL JS IS NOT SUPPORTED (INSUFFICIENT WEBGL SUPPORT)

This needs to be fixed before this Chrome release becomes mainline.

 - kv, Karen

**Comment by asheemmamoowala** [comment]
@KarenRei Can you share more information about your hardware and whether other WebGL applications continue to work?

**Comment by KarenRei** [comment]
Hmm, curious.

When I go to a webgl test page in my (newly updated) version of Chrome, it says "This browser supports WebGL 2, but it is disabled or unavailable." Yet when I go to the same site in Firefox, it says "This browser supports WebGL 2". Note that Mapbox-based sites worked fine before Chrome was updated.

So is this a Chrome bug rather than a Mapbox bug?

As for hardware, I'm not sure what you want. lspci shows: 

00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
04:00.0 3D controller: NVIDIA Corporation GK208BM [GeForce 920M] (rev a1)

**Comment by asheemmamoowala** [comment]
> So is this a Chrome bug rather than a Mapbox bug?

Yes. If the browser is making the WebGL context  unavailable, it is outside of Mapbox's code

**Comment by KarenRei** [comment]
Okay, found a hack to make it work in Chrome (modified the flags to disable hardware acceleration).

Thanks for the tip   :)
